"""The refactored code with `legacy=True` against the goldens of the pre-refactor code.

Float64 on CPU: with fp32 the MeZO feature is decided at rounding level (docs F8), so identity
is only meaningful in float64. The goldens are generated by tests/equivalence/generate_golden.py.
"""

import numpy as np
import pytest
import torch
from equivalence.golden import assert_same, load
from equivalence.helpers import NUM_LAYERS, build, lora_state, make_args, model_fp64

from colm.data.get_training_dataset import (
    SupervisedCollator,
    get_training_dataset,
)
from colm.selection import pool as pool_module
from colm.selection.select import CoresetSelector
from colm.selection.zo import per_sample_loss, zo_parameters
from colm.train import trainers

LEGACY = dict(legacy=True)


def test_collated_batches(tokenizer, mixture_file):
    golden = load("data")
    dataset = get_training_dataset([mixture_file], tokenizer=tokenizer, max_seq_length=512)
    assert len(dataset) == golden["len"]
    assert dataset.all_data_sources == golden["all_data_sources"]
    collator = SupervisedCollator(tokenizer, legacy=True)
    for start, expected in zip((0, 4, 8, 13), golden["batches"], strict=True):
        batch = collator([dataset[i] for i in range(start, start + 4)])
        meta = batch["colm_meta"]
        assert_same(batch["input_ids"], expected["input_ids"])
        assert_same(batch["labels"], expected["labels"])
        assert_same(batch["attention_mask"].long(), expected["attention_mask"])
        assert meta["sources"].tolist() == expected["sources"]
        assert meta["indices"].tolist() == expected["indices"]
        assert meta["completion_lengths"].tolist() == expected["completion_lengths"]


@pytest.mark.parametrize("case", range(15))
def test_selection_stages(tmp_path, tokenizer, case):
    golden = load("select")[case]
    args = make_args(
        tmp_path,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=32,
        small_batch_ratio=0.5,
        **golden["over"],
        **LEGACY,
    )
    model = model_fp64(tokenizer)
    params = zo_parameters(model, args.last_layers, args.last_layer_index)
    selector = CoresetSelector(
        args, NUM_LAYERS, weight_prior=lambda: torch.cat([p.flatten() for _, p in params])
    )
    for step in golden["steps"]:
        torch.manual_seed(step["step"])
        np.random.seed(step["step"])
        selection = selector(step["feats"].clone(), step["sources"], 16, step["step"])
        assert selection.indices == step["selected"], f"case {golden['over']} step {step['step']}"
        assert selection.weights == step["weights"]
    assert_same(selector.prev_m, golden["prev_m"])
    assert_same(selector.prev_v, golden["prev_v"])


def _pool_batches(trainer):
    return next(iter(trainer.get_train_dataloader()))["micro_batches"]


@pytest.mark.parametrize(
    "unit", ["rep", "mezo", "masked_grad", "completion_length", "length_loss_weighted"]
)
def test_features_of_each_unit(tmp_path, tokenizer, mixture_file, unit):
    golden = load("features")
    args = make_args(
        tmp_path,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        data_selection_unit=unit,
        keep_sources="",
        **LEGACY,
    )
    trainer, model = build(args, tokenizer, mixture_file)
    features = []
    for batch in _pool_batches(trainer)[:3]:
        torch.manual_seed(5)
        model.train()
        if trainer.extractor.mode is not None:
            model.train(trainer.extractor.mode == "train")
        features.append(trainer._features(batch))
    for got, want in zip(features, golden[unit], strict=True):
        assert_same(got.reshape(want.shape).to(want.dtype), want, unit)
    assert_same(
        lora_state(model), golden[unit + "_param"], f"{unit}: parameters after the estimate"
    )


def test_efficient_features_and_losses(tmp_path, tokenizer, mixture_file):
    golden = load("features")
    args = make_args(
        tmp_path,
        per_device_train_batch_size=4,
        gradient_accumulation_steps=2,
        efficient_mezo=True,
        keep_sources="",
        **LEGACY,
    )
    trainer, model = build(args, tokenizer, mixture_file)
    batches = _pool_batches(trainer)
    model.eval()
    for batch, want in zip(batches, golden["efficient"], strict=True):
        assert_same(trainer.extractor.extract(batch), want)
    split = trainer.extractor.split
    with torch.no_grad():
        state = split.prefix(batches[0]["input_ids"], batches[0]["attention_mask"])
        loss = per_sample_loss(split.logits(state), batches[0]["labels"], legacy=True)
    assert_same(loss, golden["efficient_loss"])
    assert_same(lora_state(model), golden["efficient_param"], "parameters after the estimate")


TRAJECTORIES = {
    "custom": dict(
        per_device_train_batch_size=2, gradient_accumulation_steps=2, data_selection_method="none"
    ),
    "efficient": dict(
        per_device_train_batch_size=4,
        gradient_accumulation_steps=2,
        efficient_mezo=True,
        keep_sources="0",
    ),
    "efficient_nokeep": dict(
        per_device_train_batch_size=4,
        gradient_accumulation_steps=2,
        efficient_mezo=True,
        keep_sources="",
    ),
    "efficient_dropout": dict(
        per_device_train_batch_size=4,
        gradient_accumulation_steps=2,
        efficient_mezo=True,
        keep_sources="0",
    ),
    "subset_mezo": dict(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        data_selection_unit="mezo",
        keep_sources="0",
    ),
    "subset_mezo_weighted": dict(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        data_selection_unit="mezo",
        keep_sources="",
        data_selection_method="weightedsubmodlib",
    ),
    "subset_rep": dict(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        data_selection_unit="rep",
        keep_sources="",
    ),
    "subset_masked_grad": dict(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        data_selection_unit="masked_grad",
        keep_sources="",
    ),
    "subset_completion_length": dict(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        data_selection_unit="completion_length",
        keep_sources="",
    ),
    "subset_length_loss": dict(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        data_selection_unit="length_loss_weighted",
        keep_sources="",
    ),
}


@pytest.mark.parametrize("name", list(TRAJECTORIES))
def test_training_trajectory(tmp_path, tokenizer, mixture_file, monkeypatch, name):
    golden = load("trajectories")[name]
    args = make_args(tmp_path, **TRAJECTORIES[name], **LEGACY)
    dropout = 0.2 if name.endswith("dropout") else 0.0
    trainer, model = build(args, tokenizer, mixture_file, lora_dropout=dropout)

    pools, trained, rng = [], [], []
    if args.coreset:
        gathered = pool_module.all_gather_object

        def record_pool(obj):
            out = gathered(obj)
            pools.append([int(e["colm_meta"]["indices"]) for chunk in out for e in chunk])
            return out

        monkeypatch.setattr(trainers, "all_gather_object", record_pool)
        sub_batches = trainer._sub_batches

        def record_sub_batches(examples, weights):
            out = sub_batches(examples, weights)
            for batch, weight in out:
                trained.append(
                    {
                        "step": trainer.state.global_step,
                        "indices": batch["colm_meta"]["indices"].tolist(),
                        "weight": None if args.efficient_mezo else weight,
                    }
                )
            return out

        trainer._sub_batches = record_sub_batches
        loss_fn = trainer.compute_loss

        def compute_loss(model, inputs, **kw):
            if not rng or rng[-1][0] != trainer.state.global_step:
                rng.append((trainer.state.global_step, torch.get_rng_state().clone()))
            return loss_fn(model, inputs, **kw)

        trainer.compute_loss = compute_loss
    trainer.train()

    logs = [
        {k: v for k, v in h.items() if k in ("step", "loss", "grad_norm", "learning_rate")}
        for h in trainer.state.log_history
        if "loss" in h
    ]
    assert len(logs) == len(golden["log"])
    for got, want in zip(logs, golden["log"], strict=True):
        assert got["step"] == want["step"]
        for key in ("loss", "grad_norm", "learning_rate"):
            assert got[key] == pytest.approx(want[key], rel=1e-9, abs=1e-12), (name, key)
    assert_same(lora_state(model), golden["lora"], f"{name}: LoRA weights", atol=1e-10)
    if args.coreset:
        assert len(pools) == len(golden["selections"])
        for pool, want in zip(pools, golden["selections"], strict=True):
            assert pool == want["pool"]
        assert len(trained) == len(golden["trained"])
        for got, want in zip(trained, golden["trained"], strict=True):
            assert got["step"] == want["step"] and got["indices"] == want["indices"], name
            assert got["weight"] == want["weight"], name
        for got, want in zip([s for _, s in rng], golden["rng_at_train_start"], strict=True):
            assert torch.equal(got, want), f"{name}: the RNG state after selection differs"
